In [514]:
import pandas as pd

In [515]:
df = pd.DataFrame([11,22,33,44,55],columns=["Col_Name"])
df

   Col_Name
0        11
1        22
2        33
3        44
4        55

In [516]:
data = {
    "Name" : ["Dhruv","Ansh","Shubham","Neel"],
    "Age" : [21,21,20,16],
    "Salary" : [50000,45000,40000,30000],
}

df=pd.DataFrame(data)
df

      Name  Age  Salary
0    Dhruv   21   50000
1     Ansh   21   45000
2  Shubham   20   40000
3     Neel   16   30000

In [517]:
df.head(2)

    Name  Age  Salary
0  Dhruv   21   50000
1   Ansh   21   45000

In [518]:
df.tail(3)

      Name  Age  Salary
1     Ansh   21   45000
2  Shubham   20   40000
3     Neel   16   30000

In [519]:
df.describe()

             Age        Salary
count   4.000000      4.000000
mean   19.500000  41250.000000
std     2.380476   8539.125638
min    16.000000  30000.000000
25%    19.000000  37500.000000
50%    20.500000  42500.000000
75%    21.000000  46250.000000
max    21.000000  50000.000000

In [520]:
df1 = df.rename(columns = {"Salary" : "Monthly_Sal"})
df1

      Name  Age  Monthly_Sal
0    Dhruv   21        50000
1     Ansh   21        45000
2  Shubham   20        40000
3     Neel   16        30000

In [521]:
df.to_csv("Pandas.csv", index = "False")

In [522]:
pd.read_csv("Pandas.csv",index_col=0)

      Name  Age  Salary
0    Dhruv   21   50000
1     Ansh   21   45000
2  Shubham   20   40000
3     Neel   16   30000

Rows and Columns Selection

In [523]:
df[['Name','Age']]      # Can select single or multiple columns by comma sepration

      Name  Age
0    Dhruv   21
1     Ansh   21
2  Shubham   20
3     Neel   16

In [524]:
df.loc[0:2]       # Selection rows / Last index included

      Name  Age  Salary
0    Dhruv   21   50000
1     Ansh   21   45000
2  Shubham   20   40000

In [525]:
df.iloc[0:2]        # Last index is'nt included

    Name  Age  Salary
0  Dhruv   21   50000
1   Ansh   21   45000

Filtering DataFrame

In [526]:
[df['Age'] >= 19]   # Does'nt show names

[0     True
 1     True
 2     True
 3    False
 Name: Age, dtype: bool]

In [527]:
df[df['Age'] >= 19]     # Just use df at the start

      Name  Age  Salary
0    Dhruv   21   50000
1     Ansh   21   45000
2  Shubham   20   40000

In [528]:
df[(df['Age'] >= 18 ) & (df['Salary'] >= 30000 )]       # Multiple conditions at the same time

      Name  Age  Salary
0    Dhruv   21   50000
1     Ansh   21   45000
2  Shubham   20   40000

In [529]:
df.where(df['Age'] >= 20)

      Name   Age   Salary
0    Dhruv  21.0  50000.0
1     Ansh  21.0  45000.0
2  Shubham  20.0  40000.0
3      NaN   NaN      NaN

In [530]:
df.where(df['Age'] >= 20, other='Null')     # other keyword used to fill null

      Name   Age Salary
0    Dhruv    21  50000
1     Ansh    21  45000
2  Shubham    20  40000
3     Null  Null   Null

Rows and Columns Operations (Add, update, delete)

In [531]:
df

      Name  Age  Salary
0    Dhruv   21   50000
1     Ansh   21   45000
2  Shubham   20   40000
3     Neel   16   30000

In [532]:
df['Team'] = ['Owner','Team Leader','Creatives','Co Owner']     # Creating a new column
df

      Name  Age  Salary         Team
0    Dhruv   21   50000        Owner
1     Ansh   21   45000  Team Leader
2  Shubham   20   40000    Creatives
3     Neel   16   30000     Co Owner

In [533]:
df['Incentives'] = df['Salary'] * 0.5       # Creating a new column using previous data
df

      Name  Age  Salary         Team  Incentives
0    Dhruv   21   50000        Owner     25000.0
1     Ansh   21   45000  Team Leader     22500.0
2  Shubham   20   40000    Creatives     20000.0
3     Neel   16   30000     Co Owner     15000.0

In [534]:
df.loc[len(df)] = ['Rohan', 20, 35000, 'IT', 17500]      # Adding a new row at the end of dataframe 
df

      Name  Age  Salary         Team  Incentives
0    Dhruv   21   50000        Owner     25000.0
1     Ansh   21   45000  Team Leader     22500.0
2  Shubham   20   40000    Creatives     20000.0
3     Neel   16   30000     Co Owner     15000.0
4    Rohan   20   35000           IT     17500.0

In [535]:
df.loc[0 , 'Salary'] = 55000       # Updating rows based on index value
df

      Name  Age  Salary         Team  Incentives
0    Dhruv   21   55000        Owner     25000.0
1     Ansh   21   45000  Team Leader     22500.0
2  Shubham   20   40000    Creatives     20000.0
3     Neel   16   30000     Co Owner     15000.0
4    Rohan   20   35000           IT     17500.0

In [536]:
df.loc[df.Name=="Neel", "Salary"] = 50000       # Updating dataframe based on column-value
df

      Name  Age  Salary         Team  Incentives
0    Dhruv   21   55000        Owner     25000.0
1     Ansh   21   45000  Team Leader     22500.0
2  Shubham   20   40000    Creatives     20000.0
3     Neel   16   50000     Co Owner     15000.0
4    Rohan   20   35000           IT     17500.0

Deleting Values(Rows and Columns) Axis = 0 by default (0=rows,1=column)

In [537]:
df=df.drop(df[df.Name=="Rohan"].index) # Deleting row
df

      Name  Age  Salary         Team  Incentives
0    Dhruv   21   55000        Owner     25000.0
1     Ansh   21   45000  Team Leader     22500.0
2  Shubham   20   40000    Creatives     20000.0
3     Neel   16   50000     Co Owner     15000.0

In [538]:
df.drop("Incentives", axis=1, inplace=True)     # Deleting a column 

# For deleting multiple columns df.drop("Incenetives","Team", axis=1 , inplace=1)

In [539]:
df

      Name  Age  Salary         Team
0    Dhruv   21   55000        Owner
1     Ansh   21   45000  Team Leader
2  Shubham   20   40000    Creatives
3     Neel   16   50000     Co Owner

In [540]:
df.sort_values("Salary")        # By default ascending

      Name  Age  Salary         Team
2  Shubham   20   40000    Creatives
1     Ansh   21   45000  Team Leader
3     Neel   16   50000     Co Owner
0    Dhruv   21   55000        Owner

In [541]:
df.sort_values("Salary" , ascending = False)

      Name  Age  Salary         Team
0    Dhruv   21   55000        Owner
3     Neel   16   50000     Co Owner
1     Ansh   21   45000  Team Leader
2  Shubham   20   40000    Creatives

Working with Date Values

In [542]:
df["DOJ"] = ["01-01-2024", "02-02-2025", "03-03-2024", "04-04-2026"]
df

      Name  Age  Salary         Team         DOJ
0    Dhruv   21   55000        Owner  01-01-2024
1     Ansh   21   45000  Team Leader  02-02-2025
2  Shubham   20   40000    Creatives  03-03-2024
3     Neel   16   50000     Co Owner  04-04-2026

In [543]:
df["DOJ"].dtype

In [544]:
df['DOJ'] = pd.to_datetime(df["DOJ"] , format= '%d-%m-%Y')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
 3   Team    4 non-null      str
 4   DOJ     4 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(2), str(2)
memory usage: 292.0 bytes

In [545]:
df["DOJ"].dt.year   # For accessing year only
df["DOJ"].dt.month  # For accessing month only
df["DOJ"].dt.day    # For accessing day only
df["DOJ"].dt.day_name()     # For accessing day_name only

0      Monday
1      Sunday
2      Sunday
3    Saturday
Name: DOJ, dtype: str

In [546]:
df["DOJ"] + pd.Timedelta(days = 90)     # Adds 90 days to doj values

0   2024-03-31
1   2025-05-03
2   2024-06-01
3   2026-07-03
Name: DOJ, dtype: datetime64[us]

Handling Missing Values

In [547]:
df

      Name  Age  Salary         Team        DOJ
0    Dhruv   21   55000        Owner 2024-01-01
1     Ansh   21   45000  Team Leader 2025-02-02
2  Shubham   20   40000    Creatives 2024-03-03
3     Neel   16   50000     Co Owner 2026-04-04

In [548]:
df.isnull()

    Name    Age  Salary   Team    DOJ
0  False  False   False  False  False
1  False  False   False  False  False
2  False  False   False  False  False
3  False  False   False  False  False

In [549]:
import numpy as np

In [550]:
df.loc[df.Name == "Ansh" , "Salary" ] =  np.nan
df

      Name  Age   Salary         Team        DOJ
0    Dhruv   21  55000.0        Owner 2024-01-01
1     Ansh   21      NaN  Team Leader 2025-02-02
2  Shubham   20  40000.0    Creatives 2024-03-03
3     Neel   16  50000.0     Co Owner 2026-04-04

In [551]:
df.isnull()

    Name    Age  Salary   Team    DOJ
0  False  False   False  False  False
1  False  False    True  False  False
2  False  False   False  False  False
3  False  False   False  False  False

In [552]:
df.isnull().sum()   # Gives the total count

Name      0
Age       0
Salary    1
Team      0
DOJ       0
dtype: int64

In [553]:
df.fillna(0)

      Name  Age   Salary         Team        DOJ
0    Dhruv   21  55000.0        Owner 2024-01-01
1     Ansh   21      0.0  Team Leader 2025-02-02
2  Shubham   20  40000.0    Creatives 2024-03-03
3     Neel   16  50000.0     Co Owner 2026-04-04

In [554]:
df["Month"] = df['DOJ'].dt.month

Aggregation and Group By

In [555]:
df['Month'].value_counts()

Month
1    1
2    1
3    1
4    1
Name: count, dtype: int64

In [556]:
df[df['Month']==1].value_counts() # frequency of values in month column where month=1

Name   Age  Salary   Team   DOJ         Month
Dhruv  21   55000.0  Owner  2024-01-01  1        1
Name: count, dtype: int64

In [557]:
df = pd.read_csv("Pandas.csv")

In [558]:
df.groupby('Age')['Salary'].sum()   # Group by with aggregation

Age
16    30000
20    40000
21    95000
Name: Salary, dtype: int64

In [559]:
df.groupby('Age').agg({'Salary': 'mean', 'Name': 'count'})  # Using multiple aggregation using agg function

      Salary  Name
Age
16   30000.0     1
20   40000.0     1
21   47500.0     2

Concatenate and Merge DataFrames (JOINS)

In [560]:
df1 = pd.DataFrame({"ID" : [1,2,3,3,4] , "Score" : [19,15,17,10,16]})
df2 = pd.DataFrame({"ID" : [3,1,4,2,4] , "Name" : ['D','C','B','D','A']})

pd.concat([df1,df2] , axis=1)

   ID  Score  ID Name
0   1     19   3    D
1   2     15   1    C
2   3     17   4    B
3   3     10   2    D
4   4     16   4    A

In [561]:
# Merging / Joining Tables

pd.merge(df1 , df2 , how = 'inner' , on = 'ID')

   ID  Score Name
0   1     19    C
1   2     15    D
2   3     17    D
3   3     10    D
4   4     16    B
5   4     16    A

In [563]:
df

   Unnamed: 0     Name  Age  Salary
0           0    Dhruv   21   50000
1           1     Ansh   21   45000
2           2  Shubham   20   40000
3           3     Neel   16   30000